SOURCE: 'WebSearchVehicle' 
TARGET: 'VeRi'

MODEL: 'WDCNet'
TRAINER: 'BaseTrainer'

WIDTH: 224
HEIGHT: 224

BATCHSIZE: 36
INSTANCE: 4
EPOCHS: 40 
EPOCHS_PER_ITER: 60 

OPTIM: 'Adam'
MILESTONES: [10, 20, 30, 40]
GAMMA: 0.6
WARMUP_FACTOR: 0.01
WARMUP_ITERS: 10
WARMUP_METHOD: 'linear'
LR: 0.001
WEIGHT_DECAY: 0.0005
WEIGHT_DECAY_BIAS: 0.0005 
BIAS_LR_FACTOR: 1

FIRST_STEP_CLUSTERING_RATIO: 0.0075
SECOND_STEP_CLUSTERING_RATIO: 0.0075

LOGS: 'baseline'
PRETRAIN: 'None'
