SOURCE: 'WebSearchVehicle' 
TARGET: 'VeRi'

MODEL: 'WDCNet'
TRAINER: 'WDCTrainer'

WIDTH: 224
HEIGHT: 224

BATCHSIZE: 72
INSTANCE: 3
EPOCHS: 40 
EPOCHS_PER_ITER: 12

OPTIM: 'Adam'
MILESTONES: [156, 228, 300]
GAMMA: 0.6
WARMUP_FACTOR: 0.01
WARMUP_ITERS: 10
WARMUP_METHOD: 'linear'
LR: 0.00001
WEIGHT_DECAY: 0.0005
WEIGHT_DECAY_BIAS: 0.0005 
BIAS_LR_FACTOR: 1

FIRST_STEP_CLUSTERING_RATIO: 0.005
SECOND_STEP_CLUSTERING_RATIO: 0.005


ALPHA: 1.0
DELTA: 1.0
MARGIN: 1.2

LOGS: 'wdc'

PRETRAIN: 'ckpt/baseline/checkpoint.pth'
